Run action fast
Ilshidur/action-slack pull request #70
Opened 2020-08-24 18:42 UTC by itsmelion

#### Motivation:
Build time, and time is money. (ye.. they charge for build time, haha) and is just not fair a slack message consume so much  in the build process.

#### Interests:
#64 

#### What i've done:
- Skip docker build (use native node from GitHub environment)
- Build the action with [@vercel/ncc](https://github.com/vercel/ncc) as recommended in [Actions docs](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) This way we don't conflict with the host Repo, and don't even need to waste time installing our own deps.

2020-08-26 12:20 UTC, Ilshidur commented
Hello Christopher. I currently don't have a lot of time those days to get done with my TODOs, so this PR is very welcome.
This looks **really** nice, by the way ! I'll review this very soon. Thanks for the work. I hope people will like it.

2020-09-07 16:24 UTC, Ilshidur requested changes
Ok so this was about time for a review (sorry for the waiting :smile:).
This looks perfect. I'll try to test it further tomorrow. In the meantime, feel free let me know what you think of my tiny suggestions.

I really appreciate your PR. Thank you for this work. As you've been clearly improving the quality of this repo, would you like to join as a collaborator ?

2020-09-07 16:24 UTC, Ilshidur commented on .github/workflows/main.yml
> +      uses: Ilshidur/action-slack@v2
**Personal TODO :** update this once I cut a new release with these changes. I'll release it under the `2.1.0` version.

2020-09-07 16:24 UTC, Ilshidur commented on entrypoint.js
> +})();
```suggestion
if (!process.exitCode) {
  core.info("Sending message ...");

  axios.post(process.env.SLACK_WEBHOOK, message.get())
    .then(() => {
      process.exitCode = 0;
      return core.info('Message sent! Shutting down ...');
    })
    .catch((err) => {
      process.exitCode = 1;
      const errMessage = err.response ? err.response.data : err.message;
      return core.setFailed(`Error: ${errMessage}`);
    })
}
```

I guess we can remove this `(() => { /* code... */ })()` thing as I primarily used it to make the POST call with a top-level `async`/`await` handling.

2020-09-07 18:11 UTC, itsmelion commented on .github/dependabot.yml
> +
I guess vulnerability checks for Dependabot need to be activated in the `> Security` tab ([see where](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates#managing-github-dependabot-security-updates-for-your-repositories)), here is just for updates. 

Ye, I've been experimenting both Dependabot and renovate, and i like dependabot, seems faster to respond to changes in the repo that renovate.
Renovate so far has more options to configure, so on my repo's ive been using both (and dealing with the noise haha)
With both active they will be redundant most times, but it's all fine.

2020-09-07 18:16 UTC, itsmelion commented
Changes pushed!
@Ilshidur That's great! yea.. (i've been using it alot as well).
all good to me. I will be glad to help as collaborator.

2020-09-08 16:01 UTC, Ilshidur commented
Ok, so I tested it and it works as expected. Merging...

I also added you to the repository. Thanks !

2020-09-08 16:03 UTC, Ilshidur approved these changes
All good.

2020-09-08 16:04 UTC, merged